### ISSUE TITLE
File build/linux.sh with wrong line ending

### ISSUE THREAD

**Issue by wcomnisky** [usb4java/libusb4java#1]
Executing the file <code>build/linux.sh</code> I was getting the following error:
`bash: ./linux.sh: /bin/bash^M: bad interpreter: No such file or directory`

It's related to the line ending used in this file (CRLF). Should be LF.

**Comment by kayahr** [comment]
Can't reproduce this. The line-ending looks correct to me. The library is automatically build by CI systems, three of them (x86, x86_64, arm) are Linux machines and they have no problems executing this file. Maybe you have a local `core.autocrlf` configuration which causes conversion to windows-style line-endings? Check by executing this in your libusb4java checkout:

```
$ git config core.autocrlf
```

**Comment by wcomnisky** [comment]
The `core.autocrlf` is off.

<pre>
$ git --version
git version 2.5.0
</pre>

<pre>
$ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
</pre>

<pre>
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
</pre>

I'm gonna test it again tomorrow and reply here later..

**Comment by wcomnisky** [comment]
You're right!

I was using some scripts attached in my .bashrc and using a clear environment didn't happen.

Thanks
