### ISSUE TITLE
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.lang.UnsatisfiedLinkError: org.usb4java.LibUsb.init(Lorg/usb4java/Context;)

### ISSUE THREAD

**Issue by hoangtu92** [usb4java/libusb4java#7]
Hi. I tried add to my src folder but still Im not be able to use this library. 
I have tried to use MS32 but i got other error which saying not supported. here is the screenshot of my project's structure:  https://imgur.com/a/2oBeZuT

can  anyone help me please. thank you

**Comment by kayahr** [comment]
According to your screenshot you placed the libusb.dll library in your project. This can't work. You have to use the libusb4java.dll library.
