### ISSUE TITLE
Switch to libusb GitHub repo for build and support building libusb-Trunk

### ISSUE THREAD

**Issue by git-moss** [usb4java/libusb4java#8]
First a big thank you for making this library available!

Since I quickly needed a bugfix from the libusb-trunk (to fix this: https://github.com/libusb/libusb/issues/519) I modified (quick and dirty) the build script to build from the libusb GitHub master.
I think in general it would be better to grab the source code from the GitHub tags.

Attached is my quick&dirty modification.

[build-github-master.zip](https://github.com/usb4java/libusb4java/files/2776536/build-github-master.zip)

**Comment by llongi** [comment]
Fixed in https://github.com/usb4java/libusb4java/pull/10, thank you for your contribution!
